# Generated by Django 4.0.2 on 2022-05-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(db_index=True, default='FncNmpZoRaQV', max_length=40, unique=True),
        ),
    ]
