# Generated by Django 4.0.2 on 2022-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(db_index=True, default='a0rryTLRS2Io', max_length=40, unique=True),
        ),
    ]
