# Generated by Django 4.0.2 on 2022-05-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_alter_meeting_uid_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(db_index=True, default='OtCaRBQF9J61', max_length=40, unique=True),
        ),
    ]
