# Generated by Django 4.0.2 on 2022-05-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meeting_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='user_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], default='Member', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(db_index=True, default='gkuZiwjDJGF1', max_length=40, unique=True),
        ),
    ]
