# Generated by Django 4.0.2 on 2022-05-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_role_user_role_alter_meeting_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(db_index=True, default='a93rwJMPCLIH', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Admin'), ('2', 'Member')], default='2'),
        ),
    ]
