# Generated by Django 4.0.2 on 2022-05-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_alter_meeting_uid_alter_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(db_index=True, default='hTOo96DRb3_3', max_length=40, unique=True),
        ),
    ]
