# Generated by Django 4.0.2 on 2022-05-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('meetings', '0010_alter_meeting_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(db_index=True, default='7XHBv6JTPReP', max_length=40, unique=True),
        ),
    ]
