# Generated by Django 4.0.2 on 2022-05-18 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('meetings', '0012_alter_meeting_uid_alter_role_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, default='8qPunNHmQCNq', max_length=40, unique=True)),
                ('target', models.CharField(max_length=512)),
                ('shared_with', models.PositiveSmallIntegerField(choices=[(1, 'Restricted'), (2, 'Team'), (3, 'Anyone')], default=1)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Viewer'), (2, 'Commenter'), (3, 'Editor')], default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='team',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(db_index=True, default='CrreAFJ17G-m', max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='MeetingInvitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Viewer'), (2, 'Commenter'), (3, 'Editor')], default=1)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('shared_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('shared_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='meetinginvitee',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('shared_group__isnull', False), ('shared_user__isnull', True)), models.Q(('shared_group__isnull', True), ('shared_user__isnull', False)), _connector='OR'), name='only_one_of_user_or_group'),
        ),
    ]
