# Generated by Django 4.0.2 on 2022-05-18 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0013_sharedlink_remove_meeting_team_alter_meeting_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(db_index=True, default='thbDH32HpkNn', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='uid',
            field=models.CharField(db_index=True, default='dOahA2GDRrqh', max_length=40, unique=True),
        ),
    ]
