# Generated by Django 4.0.2 on 2022-05-19 04:45

import datetime
from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_sharedlink_owner_alter_meeting_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 5, 19, 4, 45, 25, 889423)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='uid',
            field=models.CharField(db_index=True, default='A09RLeaH4Hmo', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='uid',
            field=models.CharField(db_index=True, default='E51I1I8i23zp', max_length=40, unique=True),
        ),
        migrations.AddConstraint(
            model_name='sharedlink',
            constraint=models.CheckConstraint(check=models.Q(('expired_at__gt', django.db.models.expressions.F('created_at')), ('expired_at__gt', django.db.models.functions.datetime.Now())), name='valid_expiration'),
        ),
    ]
